CREATE DATABASE IF NOT EXISTS dbEmpresa;

USE dbEmpresa;

CREATE TABLE IF NOT EXISTS funcionarios(
	id	INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	idade INT(11),
	cargo VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP
);

